### ISSUE TITLE
Render parking lots

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/park-tiles#105]
I think we should start rendering parking lots. There are quite a few in OpenStreetMap that aren’t being rendered in Park Tiles (http://www.nps.gov/npmap/park-tiles/#19/38.22098/-80.89441), and important context is lost because of it.

Not sure if this is a Mapbox Streets problem or something we need to do in our CartoCSS.

**Comment by makella** [comment]
Is the drop shadow color on the buildings working better than what we currently have? I'll be curious to see if that new color helps the gray of parking lots (or whatever color you choose) stand out better.

**Comment by jakecoolidge** [comment]
I didn't make any modifications to the building color and shadow for this version, though I'm seeing now that my cartocss for the buildings in much simpler at large zooms. Dropping back the opacity of the parking lots, as a first pass, seems to be a step in the right direction.

**Comment by makella** [comment]
Oh ok. It looks fine now. When I first looked the shadow looked closer to the main road color. Maybe it was my monitor.

**Comment by makella** [comment]
I am assuming that we'll be rendering parking lots from Places on Park Tiles?  If so, closing this as we would not want to render parking lots on the entire map from OSM, correct?

**Comment by jakecoolidge** [comment]
I concur--parking lots will only affect Park Tiles within NPS boundaries, and will be drawn from Places data. So we'll have that important contextual info as we move to Places data in the near future.

**Comment by makella** [comment]
closing because we are rendering parking lots from Places data in Park Tiles v3
