### ISSUE TITLE
Label long parks multiple times?

### ISSUE THREAD

**Issue by johnpauls** [nationalparkservice/park-tiles#111]
Would it be possible to label long and narrow parks, such as the C&O Canal and the Blue Ridge Parkway more than once? As it stands, if you zoom in the label can end up far away from the field of view, and this could confuse users who are not familiar with the park boundaries.

**Comment by cwlawlis802** [comment]
We are now able to do this with our new approach to park labels. We have been creating issues for units that would benefit from multiple labels, given distributed/spread out areas, which you can view a list of here: https://github.com/nationalparkservice/places-data/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Alabeling%20add%20custom%20labels.
