### ISSUE TITLE
Piscataway Park is drawn twice 

### ISSUE THREAD

**Issue by johnpauls** [nationalparkservice/park-tiles#116]
The west side of Piscatway Park is drawn twice on Park Tiles. It is in Maryland, south of Washington DC, along the Potomac River. You may have it once as "Piscataway Park" and once as "Marshall Hall"

![image](https://cloud.githubusercontent.com/assets/5996979/4809293/39ad3efa-5eaa-11e4-82d8-d345092928f2.png)

**Comment by cwlawlis802** [comment]
This will be addressed by the NCR boundary replacement here https://github.com/nationalparkservice/places-data/issues/347.
