### ISSUE TITLE
Bring in coastlines from the NPS dataset

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/park-tiles#12]

**Comment by makella** [comment]
Hoping that when we switch to terrain v2, the coastlines will get a lot better.  related to the work @jakecoolidge is doing

**Comment by cwlawlis802** [comment]
Is this something we are still looking to pursue @nateirwin?

**Comment by nateirwin** [comment]
Yeah, but I honestly don't know a good path forward. Coastlines are hard.

Maybe this isn't realistic at this point, given the current state of data available?

Thoughts, @mtaylorlong?

**Comment by mtaylorlong** [comment]
I imagine this would be difficult to pull off. Theoretically, it's doable, but I'm not sure how well it will match up with other OSM features, so it might create as many new problems as it solves. I would suggest we tackle using NPS water data inland before we attempt it at the coasts.

**Comment by nateirwin** [comment]
Sounds good, going to close this for now.
