### ISSUE TITLE
PARA boundary is missing

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#120]
http://www.nps.gov/para/index.htm

**Comment by makella** [comment]
Working with Ryan Hodge to get the latest PARA boundary he is on furlough the week of 1/5/15 but will get back with us the week of 1/12/15 when he's back in the office.

**Comment by makella** [comment]
From Ryan Hodge:

The most recent LAKE and GRCA boundaries are posted by the Lands Division on IRMA, the file was just updated in December 2014.

Polygons - https://irma.nps.gov/App/Reference/Profile/2218503

Centroids - https://irma.nps.gov/App/Reference/Profile/2218501

The LAKE and GRCA files in this file will resolve the boundary issue for those two parks that is currently on Park Tiles. The circled area on the map shows the area you should pay attention to when comparing it to the current Park Tiles.  

IMPORTANT:
There is one very important caveat for the LAKE boundary. You will see that the LAKE boundary is a multi-part polygon with an extra 2 polygons abutting the north and south rims of GRCA (in red).  These 2 extra polygons, starred in the map below, are part of the LAKE 1964 enabling legislation, but this enabling legislation was never ratified by the Hualapai Tribe who owns the land.  So please take out these 2 polygons and ONLY use the western most polygons for the LAKE boundary.  Does this explanation sound right, Mark S.?

![capture](https://cloud.githubusercontent.com/assets/1566273/5866165/12265dea-a24c-11e4-84e7-5774ab4b6a6a.PNG)

**Comment by makella** [comment]
Correction to above explanation from Mark Sappington (Natural Resource Program Manager)

Thanks for passing on the information relating to our boundaries. One correction. The Shivwits Plateau north of the Grand Canyon is not part of the Hualapai Reservation and should be depicted on the maps. The only polygon that should not be depicted is the one south of the Grand Canyon. Let me know if you have any questions. Thanks!

**Comment by makella** [comment]
I've also requested a new illustration so we make sure things are right.

**Comment by makella** [comment]
Latest from Ryan:

Mark's saying to include the starred red polygon (Shivwitz Plateau) which is north of the GRCA (Green).  The poly to the south is the Hualapai Reservation and should not be displayed.

Looks like we found our GIS guy at PARA, so that should be getting going soon.

![image](https://cloud.githubusercontent.com/assets/1566273/5946036/f06ccd62-a6ef-11e4-8e25-a69640ae0a80.png)

**Comment by ryanjhodge** [comment]
@jimmyrocks 

Last night I realized that half of the shivwits plateau polygon was accidentally left out. At the time, I did not realize that it was split up into two polygons, so I must have caused some confusion when I said "the _polygon_ north of GRCA" instead of _polygons_.

See the screenshots below:
Currently on Park Tiles:
![capture](https://cloud.githubusercontent.com/assets/4172213/9501730/d17532ae-4be1-11e5-9d65-919282f459d2.PNG)

Missing polygon indicated by star:
![capture2](https://cloud.githubusercontent.com/assets/4172213/9501740/e08e3470-4be1-11e5-8e49-be277816bc06.PNG)
