### ISSUE TITLE
Label MABI in Vermont earlier and make sure acronym in MABI (not MOBI)

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#123]
If possible, let's label both SAGA and MOBI at the same zoom level.  If both can't fit, we should label MOBI before SAGA as it is Vermont's only national park while SAGA is a national historic site.

They would like both labeled if possible, but they are pretty close to each other at small zoom levels so maybe we can switch the labeling order in which they appear.

This is also an interesting thing to consider with our labeling rules, making sure national parks get labeling precedence over other sites and if a state only has one national park to make sure that is labeled before other sites.

**Comment by adamkoz** [comment]
Hi Makella - Park acronym for VT's only National Historical Park is MABI (Not MOBI).  Marsh-Billings-Rockefeller NHP.  Thanks!

**Comment by makella** [comment]
Ah, thank you!

**Comment by makella** [comment]
this is fixed.
