### ISSUE TITLE
Update NEBE boundary

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#124]
Using Cara's updates to OSM.

**Comment by jimmyrocks** [comment]
data:

{"type":"FeatureCollection","features":[{"geometry":{"type":"Polygon","coordinates":[[[-70.9238465,41.6329503],[-70.9213277,41.6331146],[-70.9212257,41.633704],[-70.9212192,41.6339889],[-70.921167,41.634582],[-70.9212879,41.6350908],[-70.921425,41.635684],[-70.9214678,41.6359361],[-70.9217736,41.6369637],[-70.922006,41.637626],[-70.922234,41.6375524],[-70.922624,41.637416],[-70.923073,41.637316],[-70.9236424,41.6373171],[-70.923959,41.637372],[-70.924384,41.6375266],[-70.924662,41.637639],[-70.925011,41.637764],[-70.9253225,41.6378624],[-70.9256702,41.6379513],[-70.925469,41.63727],[-70.9253295,41.6365867],[-70.9252951,41.6364152],[-70.924942,41.634315],[-70.924115,41.634393],[-70.923852,41.63298],[-70.9238465,41.6329503]]]},"type":"Feature","properties":{"landuse":"Urban Park","leisure":"park","name":"New Bedford Whaling National Historical Park Boundary","website":"http://nps.gov/nebe"}},{"geometry":{"type":"Point","coordinates":[-70.921425,41.635684]},"type":"Feature","properties":{"attribution":"Office of Geographic and Environmental Information (MassGIS)","source":"massgis_import_v0.1_20071009091517"}},{"geometry":{"type":"Point","coordinates":[-70.925469,41.63727]},"type":"Feature","properties":{"attribution":"Office of Geographic and Environmental Information (MassGIS)","source":"massgis_import_v0.1_20071009091517"}},{"geometry":{"type":"Point","coordinates":[-70.924115,41.634393]},"type":"Feature","properties":{"attribution":"Office of Geographic and Environmental Information (MassGIS)","source":"massgis_import_v0.1_20071009091517"}},{"geometry":{"type":"Point","coordinates":[-70.923852,41.63298]},"type":"Feature","properties":{"attribution":"Office of Geographic and Environmental Information (MassGIS)","source":"massgis_import_v0.1_20071009091517"}},{"geometry":{"type":"Point","coordinates":[-70.921167,41.634582]},"type":"Feature","properties":{"attribution":"Office of Geographic and Environmental Information (MassGIS)","source":"massgis_import_v0.1_20071009091517"}},{"geometry":{"type":"Point","coordinates":[-70.924942,41.634315]},"type":"Feature","properties":{"attribution":"Office of Geographic and Environmental Information (MassGIS)","source":"massgis_import_v0.1_20071009091517"}},{"geometry":{"type":"Point","coordinates":[-70.922006,41.637626]},"type":"Feature","properties":{"attribution":"Office of Geographic and Environmental Information (MassGIS)","source":"massgis_import_v0.1_20071009091517"}}]}
