### ISSUE TITLE
Hydrology

### ISSUE THREAD

**Issue by brmitchell** [nationalparkservice/park-tiles#129]
Is it possible to get more detailed hydrology on the tiles? We (IMD) are starting to use the park tiles for data visualization, and it would help to see streams and smaller water bodies on the tiles. For example, MABI in Vermont has a permanent pond (The Pogue) and a stream (Pogue Stream) that do not show on the tiles. Current priorities would be parks of the Northeast Temperate Network, National Capital Region Network, and Rocky Mountain Network, since these parks currently have data in our visualization system.

**Comment by makella** [comment]
@brmitchell thank you for the useful information with regards to how Park Tiles is being used!

We definitely want to improve the hydrography in our tiles.  I will work on getting The Pogue and Pogue Stream on the map.

With regards to the other networks, that will take more time but something that is definitely on our list of things to do.  We may be able to help you in other ways with your application if you have access to detailed hydro data for these areas.  We can make you a hydro overlay that can be used in conjunction with Park Tiles and your visualized data.

Thanks,
mamata

**Comment by brmitchell** [comment]
Thanks! If it will help you with this process, we have shapefiles of water bodies, streams, and rivers clipped to a 5 mile buffer around most of the NETN parks (11 park units). Let me know if you want me to package this up and post it for you.

**Comment by makella** [comment]
Yes!  That would be great!

**Comment by brmitchell** [comment]
OK, I'm posting to BisonConnect now, you should get an e-mail shortly. Note that ROVA = ELRO, HOFR, and VAMA, and that the data for ACAD is clipped to a much smaller buffer than 5 miles because of the larger size of the park.

**Comment by nateirwin** [comment]
Moving this to the places-data repository: https://github.com/nationalparkservice/places-data/issues/114.
