### ISSUE TITLE
Ghost boundaries inside parks

### ISSUE THREAD

**Issue by johnpauls** [nationalparkservice/park-tiles#130]
Occasionally I see small segments of boundary lines inside parks. Such as this in Rock Creek

http://www.nps.gov/npmap/park-tiles/#19/38.91731/-77.08234

Or thins along the C&O Canal 

http://www.nps.gov/npmap/park-tiles/#18/38.99846/-77.24629

are these just artifacts?  Do you want them reported?

**Comment by makella** [comment]
@johnpauls yes! Thank you for letting us know.

At first look, those artifacts look like they might be "holes" in the polygons that make up the park boundaries and are therefore getting the banded outline.  We'll take a closer look at the data and report back here.

Do you happen to have boundary datasets for these two parks?

Thanks,
mamata

**Comment by johnpauls** [comment]
I think the Rock Creek issue set may be a "hole". I think the C&O Canal is a little more complicated as some of the land in that area is technically part of George Washington Memorial Parkway, and there maybe some issues involving the two boundaries not matching correctly, or the same parcel of land being assigned to both parks. 

I have some boundary data (NCRN I&M network), but I am not sure if it is any better than what you folks have.

-John Paul

**Comment by nateirwin** [comment]
Closing for now We can reopen when we get better boundary data.
