### ISSUE TITLE
Disable rendering of certain roads coming from OSM

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/park-tiles#131]
OSM mappers have contributed roads in the park boundary that under no circumstance we want to be shown on any official NPS Map: roads under contruction. This results in thousands of people, usually per day, attemtping to drive on road and some percentage of them is successfully 'till they get to the mud-filled construction zone. Can these be turned off in park tiles? We'd rather not go behing the mappers and start deleting their contributions. 
Tags:
construction	unclassified
highway	construction

**Comment by makella** [comment]
Hi Tom,

Unfortunately, there is no easy way to do this right now.  The only way we can omit features is to query out specific OSM id's which gets messy.

Can you send me the specific areas/roads you are referring to?  I'll take a closer look to see if there is another alternative.

Thanks,
mamata

**Comment by tpcolson** [comment]
![image](https://cloud.githubusercontent.com/assets/5861784/6230684/8ff26564-b68f-11e4-9822-93b3380d1ef8.png)

**Comment by tpcolson** [comment]
The only other alternative is to delete it from OSM, which would cause another set of problems. Unfortunately we won't be able to use any OSM/Places content if it shows that road, closed roads showing up on public maps is a serious and expensive problem for GRSM.

**Comment by makella** [comment]
Ok, totally understand.  Give me a little bit to talk to the team and figure out the best solution.

Thanks,
mamata

**Comment by nateirwin** [comment]
Interesting. This is classified as "type=construction" in OSM. Maybe we should roll this up to Mapbox so they can take a look in Mapbox Streets? If there is no way to differentiate, that seems to be a fairly significant bug on their end.

**Comment by makella** [comment]
After a little more digging, I see that the 'type=construction' is coming through in Mapbox's data source so we can style that type of road however we need to.  Now just to make sure, is it ok as a blanket rule for all parks to omit roads with that classification?  Also, how do we want these roads symbolized?

**Comment by nateirwin** [comment]
My inclination would be to hide type=construction altogether, but I may not be thinking this completely through. @jimmyrocks, do you have any thoughts?

**Comment by jimmyrocks** [comment]
I don't think a road that is under construction would be useful to most
people using our maps other than as a waypoint.

**Comment by makella** [comment]
Ok. I can see some places where a section of road is under construction and it might look like it just drops off but we can always wait to get feedback about that part from people using the map.

Not showing the label for construction roads will be another thing.  Below are the attributes from Mapbox Streets you'll notice no type field in the road_label data.  I'll try and figure something out.

__road__
class street_limited
oneway 0
osm_id 328097395
type construction

__road_label__
class street_limited
len 11970
name Foothills Pkwy
name_de Foothills Parkway
name_en Foothills Pkwy
name_es Foothills Parkway
name_fr Foothills Parkway
osm_id 328097395

**Comment by makella** [comment]
@tpcolson 
I'll work on removing construction roads later on today.  I'll report back here when they have been omitted from Park Tiles.

Thanks so much for the heads-up.

mamata

**Comment by makella** [comment]
I have a support ticket out to Mapbox about the labeling issue.  If it is ok with you @tpcolson I'm going to wait to hear back on that before I take these roads out so I can make all the changes at once.

**Comment by makella** [comment]
@tpcolson I heard back from Mapbox and currently, there is no way to omit labels for one road type.  They have opened a ticket to add the 'type' attribute to the road_labels layer but that could take a while.

AJ, the lead cartographer there and I discussed some different options.  Can you tell me from your experience what roads you've classified in GRSM at street_limited?  One option might be to not label those roads at all which would also remove the labels from any road that is under construction.

Thanks for your help with this!

mamata

**Comment by tpcolson** [comment]
Even without the label, the road still renders in Park Tiles. We are not allowed to show roads which are  not open to the public in official publications. The issue isn't the label, we just don't want to show unofficial roads at all, the road centerline and the label. We have used access=private for two Park Housing Access roads, that is the only other tag I can think of. This issue is related to non-NPS OSM users adding roads to the OSM database, which we cannot edit, alter, or delete without causing some sort of controversy with the original editor. We have source=NPS tag on all "approved" road centerlines in OSM, is that a tag we can use to drive what gets rendered in PT?

**Comment by makella** [comment]
Hey Tom, I understand that.  I will remove the road.  For now, there will still be a label until I figure out the best way to handle it.

There are two issues here:  not displaying any road that is under construction (which is easy) and then omitting the label for those roads (which is more challenging).  We are looking at it from two different perspectives as well... cartographically vs. real-world on the ground.

I'll think of the best solution I can and let you know when it is done.

thanks,mamata

**Comment by makella** [comment]
@tpcolson we've fixed this issue.  You see the changes either immediately or in a few minutes.  We modified both Park Tiles and Park Tiles Imagery.

http://www.nps.gov/npmap/tools/park-tiles/#13/35.7088/-83.7249

**Comment by tpcolson** [comment]
Oh wow that is perfect! Thanks! Sup will be happy!

**Comment by makella** [comment]
That's what we like to hear! :)
