### ISSUE TITLE
Add class=driveway to all maps

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#134]
All versions of Park Tiles need this class.

**Comment by makella** [comment]
We have this class in the Places data, correct?  If we do, I am not going to bother so much with making sure that we have the class rendering from OSM data.

**Comment by jakecoolidge** [comment]
We definitely have parking aisles, a subset of service roads, but driveway isn't one of the Places presets, and doesn't come up as a feature type in Editor. I think you could safely discontinue rendering the OSM driveways. For Places data we'll want to style type='Service Road' and type='Parking Aisle'. Hope that answers your question.

**Comment by makella** [comment]
Yes, that helps. Thank you. I guess the second part of your answer relates to this question: https://github.com/nationalparkservice/park-tiles/issues/159

**Comment by makella** [comment]
Closing to carry the conversation here: https://github.com/nationalparkservice/park-tiles/issues/159
