### ISSUE TITLE
Allow creation of custom CSS

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/park-tiles#138]
Related to the labels and symbolizing issue...is it possible to have some sort of front end where a park user can control some simple and basic carto css and this would render a park tile package based on the input, which would then feed back into a basemap option in builder. This would have to be geographically limited, so a custom css wouldn't applied nationwide and rendered as a large tile package. Example would be where a park wants to alter symbology of features to call attention to something or enhance labels of a certain feature. The current online Map Box web based custom thingy is the functionality I'm thinking of.

**Comment by makella** [comment]
I'm moving this as an enhancement to Builder as it is more related to that tool versus Park Tiles.
