### ISSUE TITLE
Create a version of Park Tiles that pulls in only GRSM data

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/park-tiles#142]

**Comment by jimmyrocks** [comment]
Uploaded as: nps.nps-grsm-roads-trails-test

**Comment by makella** [comment]
Great, thanks!  Will do some testing with it.

mamata

**Comment by jimmyrocks** [comment]
Road Types:
-----------------
Residential Road
Secondary Link
Trunk Link
Abandoned Railway
Tertiary Road
Primary Road
Primary Link
Service Road
Secondary Road
Trunk Road

Trail Types:
---------------
Track
Equestrian Path
Trail

**Comment by makella** [comment]
closing done by @jakecoolidge
