### ISSUE TITLE
Great Lakes double labels

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#145]
Great Lake labels have been added to OSM/Mapbox Streets data source which is causing double labels on our maps.

Simple fix in CartoCSS for all Park Tiles maps.

**Comment by jimmyrocks** [comment]
One less layer that we need to add really!

**Comment by makella** [comment]
We still need them at small scales.  Also the dataset I created helps us do the nice labeling along the line.  This is after those shut off and OSM labels kick in.  So we'll still need our Great Lakes labeling layer.

**Comment by jimmyrocks** [comment]
Ok, we can leave them then!

**Comment by makella** [comment]
done
