### ISSUE TITLE
Isle Royale disappearing at certain zoom levels

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#146]
This isn't our mistake.  It looks like there is no longer an island cut out of Lake Superior at certain zoom levels and the terrain/land are not coming through -- it looks like some tiles are not rendering properly.

This is happening in both Terrain v1 and v2 on our maps as well as Mapbox's basemaps.  I have a support ticket out to Mapbox.

Pointed out by @ryanjhodge:
<em>Maybe you are already aware of this, but keep your eye on Isle Royale while zooming In and out (all levels).  You'll see the island appear and disappear at certain zoom levels.  It's a large island so it's visible at low zoom levels. I also see similar behavior happening on some of the official MapBox basemaps, maybe we should report it to them too? </em>

**Comment by makella** [comment]
@jimmyrocks: is this a case we can make to the OSM community as well? I feel like having one of our National Parks flooded out is a good argument for better representation.  Also, if Mapbox and NPS write it would likely make for a stronger case.

From Mapbox:

You hit on an interesting/fun/frustrating thing about using OpenStreetMap data -- different users have different ways of mapping things. Unfortunately, that's what's going on with Lake Superior right now. To quote my coworker AJ:

<em>There are different ideas about how to map the great lakes (coastlines vs multipolygons) and instead of discussing picking one, everyone tries to just map it their own conflicting way all at the same time. It is a constant exasperating challenge. Lake Superior is currently mapped 3 different ways in OSM, each incomplete. In this specific case the problem is that there are 2 multipolygons representing the lake and the islands are only part of one of them. I'll post a message to the mailing list about removing one of them.</em>

I'll be sure to let you know what happens!

**Comment by jimmyrocks** [comment]
This is a problem in OSM right now too. I'm not sure what the best way to fix it is, because if I just go in and change it, someone's just going to change it back. The best way to go would be to send a message to talk-us and talk-ca. I can do that!

http://www.openstreetmap.org/#map=13/47.9729/-88.7618

**Comment by makella** [comment]
Yeah, exactly.  That's what I was wondering if you could do! Mapbox is going to also.
thanks, mamata

**Comment by makella** [comment]
Anyone willing to write the mailing list about this? I'm not familiar with how to approach these kinds of requests so any help would be appreciated... thanks!

**Comment by ryanjhodge** [comment]
Looks like @jimmyrocks is on it here:
https://lists.openstreetmap.org/pipermail/talk-us/2015-April/014776.html

If there's any OSM update work to be done, let me know - I'd be happy to lend a hand.

**Comment by jimmyrocks** [comment]
I probably should have notified the thread. There's a guy in Fort Collins,
Mike Thompson who I've been working with on some OSM stuff, and he is
really good with relations, so I put him on the task.

**Comment by makella** [comment]
@jimmyrocks thanks for the help with this. it seems to be fixed now.

http://www.nps.gov/npmap/tools/park-tiles/#10/47.8049/-88.8334
