### ISSUE TITLE
Augment Park Tiles landing page on NPMap Website

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/park-tiles#147]
I have an idea for modifying the Park Tiles landing page (nps.gov/npmap/tools/park-tiles) to house the following items.
- First to appear would be a view of Park Tiles, which can be expanded like the state pages maps.
- Below this view would be documentation for the various ways we're using Park Tiles in our maps, and instructions for others to use Park Tiles in a variety of ways. For example, during the mapathon we learned some ArcGIS users would like to pull Park Tiles directly into ArcMap--we could provide resources for doing this on our landing page. I'll be thinking of other use cases we could add here in the next few days.

**Comment by MappingKat** [comment]
I like that idea.  We have some content in the blog for that already.

**Comment by makella** [comment]
Like this idea too. I think these kinds of how-tos would fit better into our support docs.  Similar to what @MappingKat and I did for Builder.

**Comment by jakecoolidge** [comment]
Maybe we can point to support documentation on https://github.com/nationalparkservice/park-tiles/wiki from the landing page, and keep the landing page fairly paired down. If you think of anything else we should place on the landing page, let me know.

**Comment by jakecoolidge** [comment]
Okay, Nate just pointed me to nps.gov/npmap/support, and also got me up to speed on Threespot's concept for our support pages that they developed in January. I'll incorporate these frameworks into my thinking.

**Comment by nateirwin** [comment]
Moved to npmap-website and moved here: https://github.com/nationalparkservice/park-tiles/issues/147.
