### ISSUE TITLE
Implement NPMaki for Park Tiles, Park Tiles Imagery, Park Tiles Slate, Park Tiles POI

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#148]
NPMaki 1.0 needs to be styled and implemented for the Park Tiles suite.

**Comment by jakecoolidge** [comment]
I have a draft of Park Tiles Standard with the new icons visible here: http://insidemaps.nps.gov/builder/map/?mapId=93c1574b-b569-442b-a858-26344c648bd2

The transparent icons are ready to go in the stylesheet (currently commented out), so we can quickly split the NPS POIs from the basemap and into its own layer.

If this looks promising I can delve into Imagery and Slate.

**Comment by makella** [comment]
Hey Jake, these look really good.  There are a couple of minor things I see one being that the Ranger Station icons are too large at one zoom level: http://www.nps.gov/maps/embed.html?mapId=93c1574b-b569-442b-a858-26344c648bd2.  The Ranger Stations are important, but should not be given more importance (visually) compared to other features like picnic, lodging, camping, etc.

We also probably want to take another look at why the Visitor Center icons keep disappearing.  It would be great if you could look a little bit more into that and see if there is a solution we can implement across all maps.  Looking at a few different parks, it looks like the Ranger Stations are taking over the Visitor Centers pretty early on.  Can you do some comparing of what is happening on the map to the points of interest data in Places?  Are the Visitor Centers and Ranger Stations so close to each other that the Visitor Centers stop drawing?  Something really strange is going on and if you can help narrow it down we can figure out a solution.

Another idea is to see if things get better if we bring in the Ranger Stations at a larger zoom level. We could probably turn them on a lot later as the Visitor Centers are obviously one of the most important features.

Style wise, I think the icons look really good.  I'd say take what you've done here and implement on Slate and Imagery and then we can dig a little deeper into the drawing issue next week.

Also, have you tested an upload with these symbols?  How are the file sizes looking?

**Comment by jakecoolidge** [comment]
Thanks for taking a look at this. I'll adjust the Ranger Stations accordingly, and I agree, the disappearing Visitor Centers are an issue. Jimmy and I talked about it last Thursday. He showed me the code that is supposed to prioritize Visitor Centers over all other points of interest when the POI source is created, so we're not really sure what is happening. (You may have noticed a similar behavior is occurring in our live version of Park Tiles.) I'll dig a little deeper into this, and then next week we can meet briefly with Jimmy. I mainly want a synopsis of how we've dealt with this more recently, so we can identify some tactics that we haven't yet tried.

The upload is very smooth, so the file size is looking good.

**Comment by makella** [comment]
Hi Jake, yeah, I realize this is what is currently happening.  Jim and I worked together on the prioritization piece (basically symbol level drawing) so I know theoretically that is supposed to be happening too.  It would be good to look at other POIs and see if they are drawing in the correct order... is it just a case with Visitor Centers?  If the POIs are symbolized with no other features in the map, is that still happening?  What do the data in Places look like?  Are Ranger Stations so close to the Visitor Centers (i.e. they are part of the Visitor Centers) that they are getting knocked out?  One place to look at the Visitor Center/Ranger Station thing is in Yellowstone.  That is a place where it is really apparent.  In some cases like Yosemite Village it is clear that the #place_labels in Streets V5 are affecting the drawing order and that is because how things are layered in the project.yml -- if ordering of these layers is changed, place labels appear and reappear which isn't ideal because the POIs are an overlay of Park Tiles... basically, when someone uses Park Tiles without POIs it will be weird if place labels disappear and currently, that is the most common way Park Tiles is used (minus the POI overlay).  Anyway, above are just some ideas to look into and it will be good to discuss next week.

mamata

**Comment by jakecoolidge** [comment]
Here are Slate and Imagery previews. I've increased the size of Visitor Centers relative to Ranger Stations in all versions (Standard, Slate, Imagery). 

Slate: http://www.nps.gov/maps/full.html?mapId=a88d551c-9076-4752-9648-85b1c0ac53c5

Imagery: http://www.nps.gov/maps/full.html?mapId=095fa7ac-00d3-43fc-92a5-1d8742ce917a

Standard: http://www.nps.gov/maps/full.html?mapId=93c1574b-b569-442b-a858-26344c648bd2

The disappearing Visitor Center issue hasn't been resolved yet--more on this soon!

**Comment by makella** [comment]
Hi Jake,

Thanks for putting these together.  A couple of my thoughts:

- On Slate, the green VC icon is a little too neon for the map
- On Slate, I think the pure white is a little too strong.  Can we try pushing that back maybe even to a <=10% gray?
- Can you send a version of the icons over imagery without the roads?  We don't symbolize roads on our imagery map (we only label them) so it is hard to evaluate the ones you've added because the roads are getting in the way... here's an example:  http://www.nps.gov/maps/full.html?mapId=095fa7ac-00d3-43fc-92a5-1d8742ce917a

Re: drawing order I'm looking into it more as well.  It will be good to hear what you've noticed about the questions in my previous responses and compare notes.

The first time I made a Yellowstone custom map I figured out how to order the data properly so Mapnik would read it in the way I was defining.  I think what we should try is adding a DrawOrder field to the POIs and assigning each POI a numeric value based on its importance and see if that helps.  That's what I did for Yellowstone using a shapefile and TileMill.

Anyway, we can talk more about this on Monday.

**Comment by jakecoolidge** [comment]
Hi Mamata,

Roads are now transparent on the [Imagery preview](http://www.nps.gov/maps/full.html?mapId=095fa7ac-00d3-43fc-92a5-1d8742ce917a) 

With the Slate icons, I'm erring on the side of small, incremental moves. The green of the VC is dialed down to something between the bright green used in Imagery and Standard's dark green. The other icons are now a light gray as you recommended--rgb(230,230,230). I like that the POIs pop out, so maybe we can retain quality this somewhat, without the retina-piercing rgb(255,255,255). The [preview](http://www.nps.gov/maps/full.html?mapId=a88d551c-9076-4752-9648-85b1c0ac53c5) should be up-to-date.

Now, on to the drawing order, though I can continue to make adjustments to Slate and Imagery as needed.

**Comment by jakecoolidge** [comment]
I'm pretty stoked about this. Using symbolizers I'm able to wrangle the rendering order of points of interest. Visitor Centers are stable! Check it out:

http://www.nps.gov/maps/full.html?mapId=7634839f-26c1-4f1d-93c2-cb8c16c14b7f

**Comment by jakecoolidge** [comment]
For Standard, Slate, and Imagery versions of Park Tiles, I've tested the base layer (with transparent icons) and a POI overlay (with transparent labeling). Below, I've included a link to the Builder map and the Mapbox IDs for each style. At this point, I encourage the team to have a look and provide input/feedback. Most notably, the icons drawn from our new icon set, but I've made some adjustments in terms of the icon size and zoom range. If you have any questions, just let me know!

[Standard 2.2](http://www.nps.gov/maps/full.html?mapId=49250cc7-8e62-4fc3-ace5-33acceb885ac)
base layer: nps.dc86ba05
POI overlay: nps.3259d105

[Slate 2.2](http://www.nps.gov/maps/full.html?mapId=4a305d9f-4e80-4ad7-aa96-6fe90ac7c4e9)
base layer: nps.21be771b
POI overlay: nps.502a840b

[Imagery 2.2](http://www.nps.gov/maps/full.html?mapId=af03916a-af55-4b92-b901-6b3f2a0b9dc1)
base layer: nps.0eea3fbd
POI overlay: nps.08c8af87

[Park Labels 2.2](http://www.nps.gov/maps/full.html?mapId=822bc989-c740-44fb-af04-c0cdfc2f62b3)
nps.6277fc8b

[Park Labels No Interactivity 2.2](http://www.nps.gov/maps/full.html?mapId=ffc62726-f2cc-424e-a93e-51bb7f545504)
nps.f9cdb79f

[Place Labels 2.2](http://www.nps.gov/maps/full.html?mapId=52cb2066-9ff2-458f-ad63-2c7a751f6557)
nps.92d0e6a0

These have not yet been added to the Github repo, but I can attend to this once we've finalized the designs.

**Comment by makella** [comment]
Hi Jake, thanks for getting this all together.  
The new icons look really good -- this will be an exciting release.
I have looked at all three maps but have not yet had the chance to look at as many parks as I usually do to make sure things are working well everywhere.  I will try and do that later today/this weekend.  Right off the bat though, I am noticing the squished 'i' in the visitor center icon:
![screen shot 2015-05-14 at 1 51 27 pm](https://cloud.githubusercontent.com/assets/1566273/7652564/192fc0a4-facb-11e4-8cfb-4abe518f69f4.png)

I'm also still hesitant to put the restrooms on 2 zoom levels earlier than before but am curious to hear what the rest of the team has to say.

**Comment by makella** [comment]
Hi Jake, Another thought just occurred to me re: Slate icons.  Can you do the same tests that I did with the Slate basemap (inverted colors / high contrast settings) to make sure the icons are still visible? I have a feeling we might need some adjustments.

**Comment by makella** [comment]
Hi Jake,

I just tested the high contrast / inverted color setting and everything looks good.

**Comment by makella** [comment]
Hi Jake,

Again, I think the icons look great.  Thanks for the hard work implementing these!  

I've looked at all maps in detail and I think Park Tiles and Park Tiles Slate are doing well (there is a general comment about all maps at the end).  

I think some of the icons are hard to see against the imagery and I'm wondering if it is because some of the depth (shadow treatment) was removed -- this is especially true in the non-green areas of the map since they don't have a lot to contrast against?

Also, the info icon (which was a tough one with threespot) is pixelated. They had to do that in order to fit within the pixel grid -- through your tests for NPMaki for Builder and NPMaki for Park Tiles, did you find the same thing?

![screen shot 2015-05-19 at 7 26 06 am](https://cloud.githubusercontent.com/assets/1566273/7704071/659d4386-fdf9-11e4-93c3-19710bbf569e.png)

At zoom 14, the information icon looks to be larger than even the visitor center.  Is this an illusion because of the way the symbol is built?

![screen shot 2015-05-19 at 7 28 15 am](https://cloud.githubusercontent.com/assets/1566273/7704090/7dab82da-fdf9-11e4-8c0d-fe90d7fd9162.png)

I'm also seeing on all maps that between z14 and z15, the icons look to be getting smaller and then at z16 they look to be to size again. That transition is also happening around 17-18.  I wonder if there is some intermediate svg scaling we can do to make transitions like that smoother by taking the previous size, scaling it slightly to transition between zooms to the next largest size.

**Comment by makella** [comment]
Hello Everyone,

In order to get some space to upload Styles to mapbox.com for a project, I am going to delete the following:

Park Labels 2.2
nps.6277fc8b

Park Labels No Interactivity 2.2
nps.f9cdb79f

Place Labels 2.2
nps.92d0e6a0

This will not have any impact on the review of the icons against the different basemaps that Jake has linked to above.  These are our exploded layers that Jake was testing to see if the new transparent icons that he created were functioning as expected in that context.

**Comment by nateirwin** [comment]
Overall, the icons are looking great! Some comments:

The question mark icon definitely looks pixelated to me. Here's a screenshot.

![park_tiles_standard__fused__2_2_and_poi_overlay](https://cloud.githubusercontent.com/assets/10443/7708099/c635fa14-fe10-11e4-91cb-f210fa51c5c9.jpg)

Is there a way in the data to differentiate between a campground and a campsite? In this screenshot, the orange arrows are pointing to backcountry campsites. The campground in the middle is Cades Cove, one of the largest campgrounds in the park. It would be useful to show campgrounds before we show campsites, and even symbolize them slightly differently.

![park_tiles_standard__fused__2_2_and_poi_overlay](https://cloud.githubusercontent.com/assets/10443/7708174/3c1c1e0c-fe11-11e4-87b2-cfbfaf1c8459.jpg)

I'm seeing a bit of overlap between labels and icons:

![park_tiles_imagery_2_2](https://cloud.githubusercontent.com/assets/10443/7708276/cd095cc2-fe11-11e4-8912-4c6977591d3f.jpg)

I also agree that the icons don't show up great when overlaid on Park Tiles Imagery - especially in urban areas - but they are a big improvement!

**Comment by makella** [comment]
@nateirwin yes, it would be great if we could do campground/campsite based rendering. I think it would be great if we could do that for restrooms too.  At a certain zoom level just show that there are restrooms in this general area and then when zoomed in show individual locations.  Mentioning this because in my head it is like the campground/campsite idea.

**Comment by nateirwin** [comment]
I was just thinking we might be able to change the symbol based on its classification in the data.

Many backcountry campsites only have one tent pad, while many frontcountry campgrounds have several hundred campsites. To me, those are two totally different things.

We could definitely do the same with restrooms too. A vault toilet is not the same as a complex with ten stalls and showers.

Is that what you were saying?

**Comment by makella** [comment]
Oh i read campground/campsite -- but yes, along the same lines. Bottom line: a little more granularity in the data would help with symbolizing things differently depending on the purpose of the map (as we already know!)

**Comment by jakecoolidge** [comment]
Thanks, @nateirwin. I'm definitely in favor of differentiating between campsites and campgrounds. I'll work with Jimmy to get this data into the nps-places-poi source, while also developing a way to mark these sites with different symbols. A question for you guys: should we consider backcountry campsites a more specialized use-case feature that maybe we don't render on Park Tiles? In this case, we would symbolize the major campgrounds, but remove the individual backcountry sites. We would still need to make sure we were pulling in campgrounds tagged in a specific way. tourism=camp_site (campground) vs. tourism=camp_site, camp_site=pitch (campsite)

For restrooms, I'm still thinking about some sort of clustering solution. I'll need to dive into this a bit more.

The labeling overlap is also happening in our current Park Tiles, so I'll need to look into what's happening there. It shouldn't be happening, based on how the CartoCSS is written, so maybe we need to get a bit more hands-on with it. Stay tuned...

**Comment by nateirwin** [comment]
Well, backcountry campsites are a pretty important feature for large natural parks, and they are pretty much non-existent in other types of parks, so I would still classify them as important.

**Comment by makella** [comment]
One thought to test for the overlapping label/poi (which from what I can tell is mostly with road labels):

- add a small buffer to the transparent icons to make them slightly larger so the road labels thing they take up more room than they do.

just a thought to test!

**Comment by jimmyrocks** [comment]
Campground and Campsite are already defined in the rendering:
"tourism/camp_site";"Campsite";"{point}";"{"tourism":"camp_site",
"camp_site":"pitch"}"
"tourism/campground";"Campground";"{point}";"{"tourism":"camp_site"}"

But they are tagged inconsistently in places, since they were tagged rather
poorly in our source dataset.

**Comment by jakecoolidge** [comment]
I'm using nps.places_poi. In both this source and in nps.nps-places-date, the FCategory for both campsites and campgrounds is "campground". I see that they're tagged differently in Places. Maybe I'm misinterpreting what you mean by the rendering definitions?

**Comment by jimmyrocks** [comment]
Looks like you're right, campsites are getting rendered as campgrounds
I'll need to look into why

thanks for that, I'll have to get back to you.

**Comment by jakecoolidge** [comment]
You have a little time; I don't have a symbol for backcountry campsites yet! Thanks for checking into it.

**Comment by jimmyrocks** [comment]
The campsites are in there now, enjoy!

**Comment by jakecoolidge** [comment]
Current checklist:
- [ ] Test new icon sizes applied at zooms 14-17
- [ ] Develop alternatives for Information symbol (outer ring renders poorly at small sizes)
- [ ] Develop alternatives for Visitor Center symbol (in some cases the "i" renders poorly)
- [X] Resolve labeling issue
  (Labels were not acknowledging the presence of the transparent svgs. I created new transparent svgs appear to be working properly)
- [ ] Develop alternative symbols to differentiate campgrounds vs. campsites
- [ ] Consider a means to cluster restroom symbols at zoom levels greater than 20

**Comment by jakecoolidge** [comment]
New iteration! I haven't updated Slate and Imagery yet, but before I do, I thought this map should be reviewed first:

[Park Tiles Standard 2.1 demo](http://www.nps.gov/maps/full.html?mapId=49250cc7-8e62-4fc3-ace5-33acceb885ac)

It incorporates changes marked in the checklist above. If we like this direction I can begin updating Slate and Imagery.

**Comment by nateirwin** [comment]
I think it is looking really good! One question: How are the "campgrounds" up along the Appalachian Trail in GRSM tagged? I believe those are really shelters (wooden structures with bunk beds), and don't we have a shelter icon?

![park_tiles_standard__fused__2_1_and_poi_overlay](https://cloud.githubusercontent.com/assets/10443/7754747/35bd9846-ffac-11e4-9c3c-add388f17c8c.jpg)

**Comment by jakecoolidge** [comment]
We do indeed have a shelter icon. These are coming into the source with the FCategory "campground". @jimmyrocks may be able to update the rendering script--I pointed this out to him. In Editor, Sillers Bald Shelter, for example, is tagged--"amenity=shelter", "tourism=camp_site", "building=hut". The tourism tag must be what is rendering the category as a campground.

**Comment by jakecoolidge** [comment]
Jimmy updated the shelters, and I've now integrated shelters into the Park Tiles 2.1 demo.

**Comment by nateirwin** [comment]
Looks good!

**Comment by makella** [comment]
Hi Jake,
Can you give us one more option to choose from for the campground/campsite?  I definitely think what you've done looks great.  

The information icon is the only icon in the NPS set that has a symbol around a symbol -- that's why that one has a frame around it even though we removed the frame shapes from all the icons.  Since that's already how that one was (and the only one that had a shape around a shape), we decided to keep that style.  

I'd just be interested to see another option that didn't include the additional frame since none of the other symbols (other than info) have that style.

Let me know your thoughts.  

Thanks!
mamata

**Comment by nateirwin** [comment]
I definitely agree with @makella - it would be great to play around with a few more designs. I'm happy to brainstorm a bit if that would help.

**Comment by jakecoolidge** [comment]
This morning I came up with a campground symbol in which three smaller tent triangles are grouped to form a larger triangular shape. It originates from my earlier concepts but forms a more coherent graphic profile. I like that a triangular shape stands in for camping generally; a single triangle/tent for campsites, and a more complex triangle group for campgrounds.
![campground-trio-cades-cove](https://cloud.githubusercontent.com/assets/11392872/7817635/711c176a-0393-11e5-8508-e9744c656b61.png)
![campground-trio-grand-canyon-village](https://cloud.githubusercontent.com/assets/11392872/7817636/71232fa0-0393-11e5-9ec8-c59c5afc1818.png)

I have another variation in mind but I thought I'd get this one out for review.

**Comment by makella** [comment]
This is a tough symbol! What you've come up with is an interesting take on it.  Will the campground icon disappear at some point and show campsites?  If so, this makes sense to me where the campground icon with multiple tents will break up to show individual campsites.

I'm curious to see your other variation as well.  Were there any recommendations that Tom made that we could try and test out as well (are these them)?  I see this becoming a slippery slope because we might need, at some point, to differentiate between front and backcountry camping as well.  

Do you think there are going to be other symbols that will need a similar treatment? I know we talked about restrooms (general) vs. location of actual stall, but curious if there are others that you can think of.  Another one I can think of are backcountry ranger stations... It might give us some insight into some broader thinking on how to symbolize one versus many or multiple types of the same kind of feature.

**Comment by jakecoolidge** [comment]
My latest thinking on the campground icon vs. the campsite icon can be viewed here:
[centered on Cades Cove](http://www.nps.gov/maps/full.html?mapId=d2af3321-6ea5-4077-a244-db6ddadc3e48)
[centered on Grand Canyon South Rim](http://www.nps.gov/maps/full.html?mapId=f7217e08-281a-482c-9acd-14fea758c679)
In addition, I ran with a suggestion Mamata had--to support multiple categories of campsite, if necessary, by using color as a variable. This is very granular, and would be used only for a special use case. I don't see integrating this into our main symbol set for the moment. But we are thinking about what types of visual variables we can use to build variation onto an existing icon. In the maps above, the "tent" icon has been modified with a repeating linear motif to express multiples (campground). A color added to the center of icon could be another. If one or more of these strategies works, I can develop documentation to help us standardize our process. 
![campsites_campsite-colors-example](https://cloud.githubusercontent.com/assets/11392872/7847648/00773b1c-0482-11e5-98f9-fe1aeabbebd5.png)

**Comment by makella** [comment]
Hi Jake, I think this is looking a lot better and more inline with the rest of the set -- thanks for taking the time to work through this tough, but important issue!

For everyone else, a little backstory: Jake had the idea of doing the lines on the side of the tent to indicate more (ie - campground with multiple sites) we looked through the other symbols from HFC in the standard and more sets, and lines are something that are used in other symbols -- one you might be familiar with is amphitheater. 

One LAST (I promise) thought is to keep campground as it is in the HFC set and then use the tent with the dot to indicate campsite.

What do others think?

**Comment by nateirwin** [comment]
That sounds like a plan to me!

**Comment by jakecoolidge** [comment]
Okay, we're really close! Thanks for your patience as we iron this out. We're down to two options, which I've diagrammed here, side-by-side. On the left, the campground icon has additional bands, and is paired with a small tent icon to represent campsites. On the right, the campground icon is represented by normal-sized tent icons, and campsites by a small tent with a circle in the center. Zoom increases down the diagram. The last pair of images suggests how a campground icon can be replaced by individual campsites at larger scales. (Of course, we'll need to build that data into Places in the future.)

Let me know what you think and I'll get this integrated into our upcoming formal release as well as the overlays for Park Tiles 2.1.

![options-comparison_options-comparison](https://cloud.githubusercontent.com/assets/11392872/7865114/9b338f9c-0523-11e5-9f66-3f5288dc7400.png)

**Comment by makella** [comment]
@jakecoolidge which one are you thinking works best?

**Comment by jakecoolidge** [comment]
Yeah, I guess I should ping you guys, since I'm waiting to see what others have to say. But for my part, I'm leaning towards the option on the left. I know it's a bit more radical, since the regular tent icon is typically associated with campground. What I sometimes remind myself is, the campground icon has been modified in the past on print maps with a bounding box to indicate a larger magnitude campground. So in our case, we're modifying the campground icon not by adding the bounding box, but with a motif that better suits what we're looking for in terms of our web map icons.

I still like the idea of holding the small tent icon with the circle in reserve for special use cases where we have to depict a broad variety of types of campsites.

**Comment by makella** [comment]
I'm good with that. We can put it out there and see if there is any feedback... always a good way to test something out. Also, thanks for the comparison, it really helps.

If we go this direction we should probably add it to the Builder set as well and change the current name for the campground icon we have to campsite, right?

What does everyone else think?

**Comment by nateirwin** [comment]
I'd say it sounds like a plan. Like you said, I think we'll hear back quickly if people don't like the new icon ;-)

I'm happy to update Builder with the new icon set once it is ready.

**Comment by jakecoolidge** [comment]
Cool. Once the Builder set is good to go, I'll notify you.

**Comment by cwlawlis802** [comment]
Looks good to me! I like the idea of a clustered icon, especially if it can expand to identify specific campsites at given zoom levels (in parallel to [Leaflet's Markercluster](https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-markercluster/)). :+1:

**Comment by jakecoolidge** [comment]
All versions of Park Tiles have been updated to accommodate the new POI symbols, including the Github repo and our Mapbox account.
