### ISSUE TITLE
Fix roads in OSM for Big South Fork

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#150]
Chad Harrold, GIS Specialist/Geologist from Big South Fork NRRA and Obed WSR pointed out that:

"There are old Oil and gas roads on this map that basically do not exist anymore."

I asked him for a detailed screenshot of the roads that no longer exist:

"I am attaching corrections to the Park Tiles Map for Big South Fork. 
All roads in red have either naturally reclaimed or are gated and used for administrative use only and should be removed form the map.
A couple of things are mislabeled as well and are noted accordingly."

He sent a 5 pg detailed PDF with corrections.

**Comment by tpcolson** [comment]
Mamatha if you want to assign this to me I can make the edits in OSM and Places...

**Comment by makella** [comment]
Ok, great! Thanks Tom.

I'll send you the PDF from Chad via email.

**Comment by makella** [comment]
@tpcolson can you give us an update on this?

**Comment by makella** [comment]
from @tpcolson :

From: Colson, Thomas [mailto:thomas_colson@nps.gov] 
Sent: Monday, May 11, 2015 6:44 PM
To: Akella, Mamata; Benjamin Harrold; Christopher Barrow


Subject: Re: Park Tiles data
 
Chad, this has been mostly done. In the coming weeks, the NPMap team is going to be working through some edits to the park-version of the OSM database, which will update Park Tiles for the whole NPS. I am working with Barrow to make sure we have authoritative data from SER parks loaded into this system, as well as a means to serve this data to parks and public.
 
Because I drank your beer once, I'll make sure that gets into the non-park OSM database as well.
 
Chris, I have a couple of volunteers that spend every minute of their spare time editing in OSM, feel free to send more my way.
