### ISSUE TITLE
Appalachian Trail Unit Boundary Conflicts with park boundary

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/park-tiles#151]
Within GRSM, the AT unit boundary is superimposed on top/within the GRSM boundary in tiles. This could be confusing to visitors looking at this map in our CMS. Can the AT boundary be merged/truncated at the GRSM park boundary, so one contiguous park boundary is rendered?

**Comment by makella** [comment]
Hi Tom, are you saying that you would like us to not symbolize AT through your park? Like it is ok to symbolize it, but you would like it to look like a trail in your park versus matching the existing style of the rest of the line?

**Comment by tpcolson** [comment]
yes, just like any other trail (?), without the green boundary line buffering it. Not sure how the AT folks would feel about that....but our "Folks" would like the GRSM boundary to be consistent without the T boundary bisecting it, if that makes sense....

**Comment by makella** [comment]
@tpcolson I think we are going to leave this as is on Park Tiles for now.  @jakecoolidge was working on some alternative representations for AT through GRSM so he might have a solution.  We got the trail data from the AT folks and want to display their data as they want it shown as well.  I

**Comment by jakecoolidge** [comment]
Even my variations did not remove the green boundary buffering AT as it went through GRSM; they were more oriented around developing a consistent trail symbol for AT and non-AT trails, but identifying AT with an additional buffer (I think I brought the size of the buffer down slightly, but it's still visible). We would probably want to make sure the AT folks were okay with a discontinuous buffer symbol.

**Comment by tpcolson** [comment]
Besides the buffer, there appear to be some issues with two different data sources for the same trail..which show some pretty significant differences in geometry...

![image](https://cloud.githubusercontent.com/assets/5861784/8627058/67a12166-2716-11e5-95fc-162744c1d097.png)

**Comment by makella** [comment]
That is coming from OSM.  Unfortunately, we can't remove the Appalachian Trail from rendering because in OSM it is made up of so many different segments.  I tried to do it in the beginning and if we do such an intense query, our map won't upload to Mapbox.  I'll check again and see if I can do it but from what I remember, that was the issue.  I'll check again and report back.

**Comment by tpcolson** [comment]
I think I know what the problem is...and it's my fault: way back when, when I did the original OSM import, I blasted our trails into OSM, and promptly had to "smooth" them (de node) after complaints from OSM folks. So teh "Green" AT that is being pulled from OSM is the "denoded" one that I had uploaded, and the white one is the original, has-all-the-nodes one that I put into places DB. The solution here is to revisit OSM and sync the OSM version geometrically with the Places version, or do it in places. My vote is to do it in OSM.....

![image](https://cloud.githubusercontent.com/assets/5861784/8627617/2bf1cfcc-271a-11e5-8a10-3e683912fa02.png)

**Comment by makella** [comment]
Actually the green AT trail is the one we got from them and the white one
is being pulled from OSM.

**Comment by tpcolson** [comment]
I'm confused...then where is the one that is in Places? If that's the case, it'd be handy if we're only showing one trail through the park, and that's it's node-connected to all of the other trails that connect to it. GRSM Trails were inventoried with a Trimble GPS, so we're pretty confident that the trails layer posted into to places is the correct one.

**Comment by makella** [comment]
Places data currently does not show on the version of Park Tiles that we're talking about.  The green AT line is coming from our boundary data.  We swapped out the lands (buffered line polygon) of the AT with a line feature that we received from Matt Robinson - GIS Specialist
Appalachian National Scenic Trail

**Comment by tpcolson** [comment]
I think we have a bigger issue here then, two units each wanting a different version of the same trail being shown on the Tiles.

**Comment by makella** [comment]
exactly.

**Comment by makella** [comment]
i am going to move this to the places-data issues since we've determined it is a data and not cartography issue.

**Comment by tpcolson** [comment]
Spoke with Matt Robinson, we're going to get the two "versions" to be synced and the same.
