### ISSUE TITLE
Rendering artifacts

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#153]
I haven't seen this issue before, just noticed it in GRTE -- there are weird rendering artifacts showing at some (not all) zoom levels.  I'll investigate further.

http://www.nps.gov/npmap/tools/park-tiles/#17/43.90819/-110.64093

**Comment by jimmyrocks** [comment]
That is very strange, I can re-render at some point if you'd like. Although
I haven't changed the park boundaries (which looks like the problem layer)
in a while.

**Comment by makella** [comment]
@jimmyrocks, have you had a chance to re-run park boundaries?  when's the last time that was done? still seeing this artifact.

**Comment by nateirwin** [comment]
Hopefully this will be fixed with the new park boundary update, @jimmyrocks?

**Comment by cwlawlis802** [comment]
This issue does not seem to be persisting - closing.
