### ISSUE TITLE
Add POI overlays for Slate, Imagery to Park Tiles viewer

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/park-tiles#158]
Here are the MB ids for the following overlays:

Slate POI overlay: nps.502a840b

Imagery POI overlay: nps.08c8af87

**Comment by nateirwin** [comment]
Ok, this is implemented, but I can’t roll the change out to production until one issue is taken care of. The POIs don’t have interactivity turned on for these two overlays.

@makella can show you how to do this, Jake. Let me know when interactivity is turned on and I’ll get this out.

**Comment by jakecoolidge** [comment]
I think I know where this adjustment can be made. I'll give it a shot and update the repo.

**Comment by jakecoolidge** [comment]
I think the overlays needed the template parameter specified in the xml to fully support interactivity. This has been added to the styles on Mapbox and in the repo. If it's still not working let me know and I'll consult @makella.

**Comment by makella** [comment]
Hi Jake, I'll take a look in the morning but it is in the project .yml not
.xml

**Comment by makella** [comment]
This looks good to me. @jakecoolidge another way to test in the future is to click on the features in the Mapbox Studio project and/or bring the layer into Builder and check that interactivity is working.

**Comment by nateirwin** [comment]
Done. I'll deploy the update later today.
