### ISSUE TITLE
List of attributes to be symbolized in Park Tiles from Places data

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#159]
Is there a list anywhere that I can use to make sure that I am rendering all types of roads, trails, etc. from our nps.nps_places_data source?

**Comment by jakecoolidge** [comment]
I refer to the [this spreadsheet;](https://docs.google.com/spreadsheets/d/1sQZRUZDe8vPu8PANxoIc5k0Pv85xNd5ae4uGJ0fwEt0/edit#gid=1063193272) in it Chad, Angie et al have captured potential Places presets that are available to users in Places Editor.
This is the list I've compiled for use in my Places Viewer style:
    [type='Trunk Road'],
    [type='Primary Road'],
    [type='Secondary Road'],
    [type='Tertiary Road'],
    [type='Residential Road'],
    [type='Unclassified Road'],
    [type='Unknown Road'],
    [type='Trunk Link'],        //link set
    [type='Primary Link'],
    [type='Secondary Link'],
    [type='Tertiary Link'],
    [type='Service Road'],         //service set
    [type='Parking Aisle'],
    [type='Track'],                //track set
    [type='Four Wheel Drive Road'],
    [type='Motorized Track'],
    [type='Trail'],                //trail set
    [type='Sidewalk'],
    [type='Equestrian Path'],
    [type='Bicycle Trail'],
    [type='ATV Trail'],
    [type='Backcountry Ski Trail'],
    [type='Cross-Country Ski Trail'],
    [type='Dog Sled Trail'],
    [type='Downhill Ski Trail'],
    [type='Equestrian Trail'],
    [type='Four Wheel Drive Trail'],
    [type='Motorcycle Trail'],
    [type='Non-Motorized Trail'],
    [type='Snowmobile Trail'],
    [type='Snowshoe Trail'],
    [type='Path'],
    [type='Pedestrian']

**Comment by makella** [comment]
Thanks! This is helpful. Now I guess it would be good to have a conversation if all trails are equal on Park Tiles Fused and use the type attributes for more custom maps.  Also, I guess we'll need to think of some zoom dependent styling for the trail types... similar to POIs, what should show first and when?
