### ISSUE TITLE
Park Tiles 3 review

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#160]
Hello All,

Although not yet completely done (will it ever be?), I am pretty happy with where this version of Park Tiles is.  Nate made a simple viewer for comparison/review.  On the left is Park Tiles 3, on the right, Park Tiles 2.

Please take some time to look over.  I'm going to schedule some time for us tomorrow to talk through some of the major changes all of which I will not be listing here!

I will also not list the items to-do as we can discuss those tomorrow!

It will be good to talk.  Feel free to add any comments you have to this issue.

http://www.nps.gov/npmap/tools/park-tiles/compare/

Thanks,
mamata

**Comment by jimmyrocks** [comment]
This is great! I love being able to see all the places data!

**Comment by makella** [comment]
definitely exciting, eh??

**Comment by makella** [comment]
Notes:
- Add POIs transparent to middle layer see Fort Vancouver

**Comment by jimmyrocks** [comment]
There are soooo many errors in places! Hopefully this will get people to
fix them!

**Comment by makella** [comment]
LOTS of unclassified roads.

**Comment by makella** [comment]
Here is Park Tiles 3 with Tom Patterson approved Mapbox terrain v2:

http://www.nps.gov/maps/embed.html?mapId=f2088946-b59a-4ee4-a00a-318aae2470a5

**Comment by makella** [comment]
I should mention that I still need to blur things and transition out of the hillshade at large scales...

**Comment by nateirwin** [comment]
This looks great, @makella!

**Comment by makella** [comment]
thanks!

**Comment by ryanjhodge** [comment]
What do you mean by `blur things and transition out of hillshade at larger scales`? This reminded me of something I've been meaning to mention for awhile.... It occurred to me while using npmap/park tiles on my phone while at Grand Canyon last month and Zion over the weekend.  It felt a little odd to me to see the GRCA rim or the ZION canyon walls disappear on the map while standing right next to these features (zoom level >18ish?)

... just a thought I remember having... I figured maybe these terrain datasets don't have a high enough resolution or the "shadows" might interfere with other features? The terrain disappears even earlier on google maps.

I was on the rim trail around around here:
http://www.nps.gov/npmap/tools/park-tiles/#18/36.05805/-112.13922

**Comment by makella** [comment]
Hi Ryan,

Yeah, the terrain doesn't have high enough resolution to display at larger scales.  And so what I did was incrementally blur it out so by the time you are at zoom 17 it is no longer drawing.

mamata

**Comment by makella** [comment]
This is what I believe is the 'final' version of Park Tiles 3.  The VC labels need some work still.  I'll look deeper into that when I have some time.  I've also added the projects to mapbox-studio-projects repo. I did some detailed documentation in the projects themselves -- I have a little more to add but for the most part, that is done.  

http://www.nps.gov/maps/embed.html?mapId=e0debb39-2c9e-44a0-941b-077e4252692b

I know everyone's looked at the map (thank you for that) but if you have a few minutes please just peruse the URL above of the finalish version to let me know if you see any glaring errors.

Thanks,
mamata

**Comment by nateirwin** [comment]
Such a huge step forward! A few bits of feedback:

1. Is it possible to show trail labels one zoom level sooner? I find myself looking for them at zoom 15, but maybe that's too much information too early?
2. The label for Little Bighorn Battlefield at zoom level 8 is cut off (see screenshot below).

![park_tiles_3_0__final_](https://cloud.githubusercontent.com/assets/10443/8970237/c7d259bc-3605-11e5-9a3e-4eb2eda0128e.jpg)

I may have some more feedback later when I get to take a more in-depth look.

**Comment by ryanjhodge** [comment]
1. `Mapbox-Streets` roads and layers are underneath park boundaries - I'm guessing this is on purpose as I see some units have roads that I'm assuming are coming from the Places DB.  You can see road sections and cut off road labels in parks that have inholdings (e.g. GOGA and VAFO).

2. VAFO you can see Road Shield labels on top of the park, but no roads (e.g. PA23 and SR3022)

3. There are no boundaries for VALR in Hawaii. There is a label for it. A visitor center shows up in the water at zoom level 17 (This might have to do with bullet point 5 below)

4. [AMME](http://www.nps.gov/amme/) label shows up as "American Memorial NP" then as "American Memorial" and lastly as "American Memorial Park." "Park" might be getting cut off on the middle one. From AMME's website, it seems like the unit designation for this one is "Park" (but first label calls it "NP").  The only other unit I know with "Park" unit designation (as opposed to "National Park") is Catoctin Mountain Park ([CATO](http://www.nps.gov/cato/)).  There's a famous "inholding" at CATO :us: :house_with_garden: :us: that they don't even show on the park's unigrid map.

5. Possible projection issue in the Pacific Islands Region.  See screenshots of HALE and AMME below.  It looks like those boundaries should be lining up with the coast.

HALE
![capture](https://cloud.githubusercontent.com/assets/4172213/8973164/9f48833e-3616-11e5-9123-3efd860aefd1.PNG)

AMME
![capture2](https://cloud.githubusercontent.com/assets/4172213/8973173/b255a8ee-3616-11e5-8e6a-c2271fab64b0.PNG)


This last one I wouldn't say is a "glaring" issue but might warrant a separate issue in Places.

* Klondike goldrush Seattle Unit - The Visitor Center is on 2nd Ave and Jackson.  There's a brown building outline of it on the map already (from Places?). But the VC icon is currently showing up Northwest of there at Marion St and Western Ave.  I've visited this unit before and I'm pretty sure the whole unit is comprised of just one building (the VC on 2nd Ave).  The label is also "off".

**Comment by johnpauls** [comment]
Not sure this is the correct place for this as these problems are also on the prior version, but:

1) This is from the Suitland Parkway which heads east out of Washington DC.
![image](https://cloud.githubusercontent.com/assets/5996979/8982912/a9a0f5a0-3693-11e5-8468-c92c87b772c1.png)

There is a label there "National Capital Parks" which should either be Suitland Parkway or National Capital Parks East. I don't think there is anything that is called National Capital Parks.

2) There are many overlapping boundaries at this unit, such as 
 
![image](https://cloud.githubusercontent.com/assets/5996979/8983021/8d43551e-3694-11e5-8103-8e32014e4afd.png)

and

![image](https://cloud.githubusercontent.com/assets/5996979/8983035/a05f4054-3694-11e5-8b4f-17353750ebe1.png)

3) The boundary seems shifted for Jones Point Park, part of George Washington Memmorial Parkway in VA, across the river from Oxon Cove Park in MD. It looks like the lighthouse in not in the park. 

![image](https://cloud.githubusercontent.com/assets/5996979/8983111/6c4d1af6-3695-11e5-942d-86076deeed29.png)

4) Label for Lincoln Memorial is far from the building 
![image](https://cloud.githubusercontent.com/assets/5996979/8983225/80380796-3696-11e5-8795-5f636fce84cb.png)

At zoom level 14, the Korean War Veterans Memorial label is right on the Lincoln Memorial. 


That is what I have for now, but I am not sure that everything that should be labeled in DC is, as there are lots of small sites, some of which are "official" parks, and some are not, and I have to check to see which are which.

**Comment by makella** [comment]
@ryanjhodge @johnpauls 

Thanks so much for taking the time to give us feedback!

I should give you both some context about this map but before I do, please add any boundary/park labeling issues to the [places-data](https://github.com/nationalparkservice/places-data/issues) repository.  We are tracking those there.

Park Tiles 3 is a new map that we've been working on that displays data coming from Places INSIDE of park boundaries and OSM data OUTSIDE of park boundaries.  @ryanjhodge a lot of the things you notice like highway shield with no associated roads and "roads underneath park boundaries" is because of that.  The roads in fact are not under park boundaries... rather, data from Places is drawing inside and for context, we've kept the roads outside visible, but less so in comparison to NPS data.

This is something that we've wanted to do for quiet some time... have a map that displays NPS data inside of park boundaries and OSM data everywhere else and we have finally figured out how to do it. The whole purpose of the map is to highlight more than anything National Parks and the data collection efforts that the NPS is currently undertaking.  So as the data improve, so will the map!

There are some features that we are using from OSM that we currently do not maintain in Places:
- Highway shields
- Hydrography
- Hydro Labels
- Place Names
- Airports, runways, and labels

Another note is that Park Tiles 3 is not planned for release until 2016. So if you see data issues inside of park boundaries, please feel free to correct them in Places.  This prototype is more of a cartographic one and of course when our data are symbolized and visible in this way, it is a lot easier to pinpoint where corrections need to be made.

I hope this helps explain the map a little better.

Thanks again for your feedback and taking the time to look at the map in detail!

**Comment by makella** [comment]
@nateirwin I'll try labeling trails at z15.  Once we have more granularity in the data, I feel like this might be easier to achieve.

I'll check into the cut-off label.

**Comment by jakecoolidge** [comment]
It's going to be really difficult to resolve all label/poi symbol conflicts; having said that, I'm thinking about the place labels (hamlets, neighborhoods, and others with low localrank values) inside park boundaries, and how we can integrate them in a way that doesn't knock out the symbols at different zoom levels. Paiute Apartments in GRCA and Sunrise in MORA are two examples. Now that you're labeling visitor centers (a really major upgrade), I wonder if we can suppress local OSM places within park boundaries, since the VCs add that extra context? 

I'll post this now and keep looking at different parks. It's not a global problem (for example, the Cades Cove isn't near any POIs), but where there are conflicts, symbols appear, disappear, and reappear. If we remove all local place labels inside the parks, we'll lose labels like Cades Cove, though in this case it would be replaced, in a way, by the Cades Cove Visitor Center label. I'm sure this has been discussed in the past, but I'm wondering if the new design might prompt a revised approach.

**Comment by jimmyrocks** [comment]
I think a lot of these places-data issues can be assigned to our
to-be-created tasking manager.
I've been thinking about the places-boundaries / park labeling issues, and
I think we can fix most of it by allowing people to make the edits directly
to cartodb and using CartoDB as our main data source. This process would
include using an A/B testing tool when importing / updating park boundaries
from the data store.

**Comment by makella** [comment]
@jakecoolidge thanks for the comments! 

So one option has always been to put `nps_places_poi` above `place_lables` in the .yml. The only issue there is that if a place name appears and then there is a poi there, the place name will disappear.  So same issue just the other way around.

The reason I haven't done that in the past is because the version of Park Tiles that is used without POIs would have weird behavior without the context of the POI and the place label.

The best and most obvious solution is for us to get our own place names inside of parks and then label OSM places outside the boundaries and ours inside.  We'll definitely have more control that way.

But I agree, the VC label in many cases does provide the context that's needed.

**Comment by makella** [comment]
I've also figured out that the `text-min-distance` property is pretty useful.  It is just a matter of playing around with it to see what works and make sure it works in 30-40 (minimum) different parks rural and urban, etc.

**Comment by nateirwin** [comment]
Something else I just thought of: Are one-way roads symbolized properly? I don't know of any one-way roads off the top of my head to check.

**Comment by jakecoolidge** [comment]
Conzelman Road in the Marin Headlands is one-way. I don't think we have access to one-way info in the source, though. We have minzoompoly, name, osm_id, type, unit_code, and z_order.

**Comment by makella** [comment]
I'm assuming that over the next six months these things are going to be sorted out? Since it is going to be released for quiet some time think of this as a style and a pattern to move forward integrating more and better data into park boundaries.  There are a lot of things that can be improved in terms of carto attributes in Places so hoping this will get better over time.  Maybe we should start another issue somewhere for a wish list of carto attributes to be added to Places data.

**Comment by makella** [comment]
And no, there isn't any special symbology for one-way roads. I'm not even sure if that is in the attributes we have in the Mapbox Studio datasource.  If there is a list to cross reference with I can take a look.

**Comment by jimmyrocks** [comment]
The oneway tag isn't exposed in the source. I can just expose the entire
tag object so we don't need to make an issue and a separate column for each
attribute we want.

**Comment by makella** [comment]
As far as I know, these are the attributes that are available in the data source.  I took all the trail types from Jake's Places Viewer map.

````
#nps_places_roads_and_trails.line [zoom>=9] {
  
  [type='Primary Road'],
  [type='Secondary Road'] {
    ::case [zoom>=12] {
      line-color: #fff;
      [zoom>=12] { line-width: 3; }
      [zoom>=13] { line-width: 4.5; }
      [zoom>=14] { line-width: 5.5; }
      [zoom>=15] { line-width: 7; }
      [zoom>=16] { line-width: 9; }
    }
    ::fill [zoom>=9]{
      line-color: @motorway;
      [zoom<=10] { line-width: 1; }
      [zoom>=12] { line-width: 2; }
      [zoom>=13] { line-width: 3; }
      [zoom>=14] { line-width: 4; }
      [zoom>=15] { line-width: 5; }
      [zoom>=16] { line-width: 7; }
    }
  }
  
  [type='Trunk Road'],
  [type='Trunk Link'],
  [type='Secondary Link']{
    [zoom>=11] {
    line-color: @motorway;
    [zoom<=10] { line-width: 1; }
    [zoom>=12] { line-width: 1.5; }
    [zoom>=13] { line-width: 2; }
    [zoom>=14] { line-width: 2.5; }
    [zoom>=15] { line-width: 3; }
      }
  }
   
  [type='Tertiary Road'],
  [type='Residential Road'],
  [type='Service Road'] {
    ::case[zoom>=15] {
      line-color: @street_case;
      [zoom>=15] { line-width: 3; }
      [zoom>=16] { line-width: 5; }
      [zoom>=17] { line-width: 6; }
      [zoom>=18] { line-width: 7; }
    }
    ::fill[zoom>=12] {
      line-color: @street;
      [zoom<=12] {line-width: 0.5;line-opacity:0.6;} 
      [zoom>=13] { line-width: 1; }
      [zoom>=14] { line-width: 1.5; }
      [zoom>=15] { line-width: 2; }
      [zoom>=16] { line-width: 3; }
      [zoom>=17] { line-width: 4; }
      [zoom>=18] { line-width: 5; }
    }
  }
  
  [type='Unclassified Road'] {
    ::case[zoom>=15] {
      line-color: @street_case;
      [zoom>=15] { line-width: 3; }
      [zoom>=16] { line-width: 4; }
      [zoom>=17] { line-width: 5; }
      [zoom>=18] { line-width: 6; }
    }
    ::fill[zoom>=10] {
    line-color: @street;
    [zoom<=11] {line-width: 0.5; } 
    [zoom>=12] { line-width: 1; }
    [zoom>=14] { line-width: 1.5; }
    [zoom>=15] { line-width: 2; }
    [zoom>=16] { line-width: 2.5; }
    [zoom>=17] { line-width: 3.0; }
    [zoom>=18] { line-width: 4; }
  }
    }
 [type='Parking Aisle'][zoom>=16] {
    ::case [zoom>=17]{
      line-color: @street_case;
      [zoom>=16] { line-width: 4; }
      [zoom>=17] { line-width: 5; }
    }
    ::fill[zoom>=16] {
      line-color: @street;
      [zoom<=12] {line-width: 0.5;line-opacity:0.6;} 
      [zoom>=16] { line-width: 2.5; }
      [zoom>=17] { line-width: 3.0; }
    }
}
    
    [type='Four Wheel Drive Road'],
    [type='Track'],
    [type='Motorized Track']{
    ::fill [zoom>=13]{
      line-color:  darken(rgb(254,251,207),7);
      line-join: round;
      //line-dasharray: 2,3;
      [zoom<=14] {line-width: 0.5; }
      [zoom>=15] {line-width: 1; }
      [zoom>=17]{ line-width: 2; }
      //[zoom>=18]{ line-width: 3; }
  }
    ::case [zoom>=15]{
      line-color: white;
      line-join: round;
      //[zoom<=14] {line-width: 0.5; }
      [zoom>=15] {line-width: 2; }
      [zoom>=17]{ line-width: 4; }
      }
    }
    [type='Trail'],
    [type='Equestrian Trail'],
    [type='Bicycle Trail'],
    [type='ATV Trail'],
    [type='Backcountry Ski Trail'],
    [type='Cross-Country Ski Trail'],
    [type='Dog Sled Trail'],
    [type='Downhill Ski Trail'],
    [type='Four Wheel Drive Trail'],
    [type='Motorcycle Trail'],
    [type='Non-Motorized Trail'],
    [type='Snowmobile Trail'],
    [type='Snowshoe Trail'],
    [type='Path'],
    [type='Pedestrian'],
    [type='Sidewalk']{
     ::fill [zoom>=13] {
      line-color:  #a0a05d;
      line-join: round;
      [zoom>=15]{line-dasharray: 6,4;}
      [zoom<=14] {line-width: 0.5;line-dasharray:3,2; }
      [zoom>=15] {line-width: 1; }
      [zoom>=17]{ line-width: 2; }
    }
   ::case [zoom>=15]{
      line-color: @street_case;//white;
      line-opacity: 0.5;
      line-join: round;
      [zoom>=15] {line-width: 2.5; }
      [zoom>=17]{ line-width: 4; }
      }
  }
}
````

**Comment by nateirwin** [comment]
Gotcha. Yeah, I totally understand this is a work-in-progress and we need to improve the data/data source first and foremost. I was really just asking because I was curious.

**Comment by jimmyrocks** [comment]
I can add a JSON object called "tags" and that should take care of most of the other attributes we need

Currently the SQL in mbstudio is:
```sql
(SELECT nps_render_line.osm_id,
   nps_render_line.name,
   nps_render_line.type as type,
   CASE 
     WHEN z(!scale_denominator!) >= 8
    THEN the_geom ELSE NULL END as the_geom,
   (SELECT CASE 
   WHEN tags ? 'bridge' THEN 'bridge' 
   WHEN tags ? 'tunnel' THEN 'tunnel' 
   WHEN tags ? 'embankment' THEN 'embankment'
   WHEN tags ? 'cutting' THEN 'cutting'
   WHEN tags ? 'ford' THEN 'ford'
   ELSE null
   END 
FROM ways
  WHERE
   ways.id = nps_render_line.osm_id) AS structure,
   nps_render_line.z_order,
   nps_render_line.unit_code,
   render_park_polys.minzoompoly
  FROM nps_render_line
    LEFT JOIN render_park_polys ON 
 lower(render_park_polys.unit_code) = lower(nps_render_line.unit_code::text)
 WHERE nps_render_line.type IS NOT NULL) as data
```

**Comment by johnpauls** [comment]
@makella 

Thanks for the explanation - I will move over the issues next week.

I don't fully understand all the issues  being discussed, but I can see a potential drawback to the idea of using only (or mostly) Places inside the boundaries and OSM outside. The current park boundaries are the legislative boundaries rather than the fed-fee boundaries (land the NPS actually owns/manages).  In some parks (the majority?) there is a fair amount of land which is within the parks legislative boundary, but owned by private citizens, other agencies etc.  

In these places parks may be unwilling or  unable to add  data to Places - particularly if they need to GPS the locations. I suspect that Superintendents would also be uncomfortable with a system that makes it look as if privately held land is part of the park. 

If you are going to make Place a more prominent feature -which I think is a good idea- you may need to reconsider what boundaries you use for the parks or in some way indicate what is going on. I imagine that would be a pretty giant undertaking.

**Comment by makella** [comment]
@johnpauls 
Thanks for your thoughtful insight!  Over time what has been happening is that parks are providing us with the boundaries they want on public facing maps.  When we get those we replace the lands boundaries with the ones that we get from parks.  You bring up an interesting point about legislative boundaries that we have discussed several times internally.  We do have plans to spend more time on boundaries and work with more parks and regions before this map goes out.

The way that Park Tiles 3 is set up is that if a boundary is updated and different than the one we have, the map will continue the pattern of drawing OSM data outside and Places data only in the boundary that we have been provided.

I'd suggest talking to @nateirwin, @jimmyrocks, and @cwlawlis802 more about this topic as they are the ones spearheading the data efforts.

Also, I will just take a screenshot of your and @ryanjhodge boundary issues above and add them to the places-data repo.

Thanks,
mamata

**Comment by makella** [comment]
@johnpauls you can follow progress on the boundary issues you pointed out here: https://github.com/nationalparkservice/places-data/issues/87

@ryanjhodge I've separated your issues out:
https://github.com/nationalparkservice/places-data/issues/88
https://github.com/nationalparkservice/places-data/issues/89
https://github.com/nationalparkservice/places-data/issues/90
https://github.com/nationalparkservice/places-data/issues/91

**Comment by ryanjhodge** [comment]
@makella Thanks for separating those issues out.

@johnpauls Keep in mind that you can customize Park Tiles to fit your needs. The map can be "exploded" out into individual layers, e.g. boundaries, surface water, terrain, park labels, etc.  You can create a composite of these individual layers in any order.  It's just a matter of comma delimiting the mapbox id's of the individual layers together. You can also turn the "Places" layer off.  

Here's an example from mapbox showing compositing.
https://www.mapbox.com/mapbox.js/example/v1.0.0/compositing/

Can also be done with the mapbox layer handler in NPMap.js
https://github.com/nationalparkservice/npmap.js/blob/master/API.md#mapbox

**Comment by nateirwin** [comment]
Hi @johnpauls: Can you give us a specific example to demonstrate the issue you outlined?

**Comment by ryanjhodge** [comment]
@nateirwin @johnpauls
We worked through an example of that situation #120 
Theres a screenshot of the legislative boundaries there (from irma) that shows hualapai land (the section south of GRCA) being part of Lake Mead.

**Comment by johnpauls** [comment]
@nateirwin   Here are a couple of examples.  

Here is Piscataway Park in Maryland from our GIS (may not be the most current data):

![image](https://cloud.githubusercontent.com/assets/5996979/9038071/6cdec2e4-39bf-11e5-91e9-7fb2a5b62d84.png)

Green is NPS owned, the areas in yellow are mostly private homes with a scenic easement and a few farms.  Large parts of the are consists of private homes on wooded lots.
Here it is from Parktiles 3 link above:

![image](https://cloud.githubusercontent.com/assets/5996979/9038692/4e79862c-39c4-11e5-90f3-916f90e59b46.png)


Currently, the park appears to be one large natural area, are all the local roads and private homes are hidden. Also,there are road segments that go nowhere as only the parts on NPS owned land are displayed. Note also River Road on the far west side. If you zoom in you see:
![image](https://cloud.githubusercontent.com/assets/5996979/9038186/7342c8fa-39c0-11e5-84ac-ef46e95e5a0b.png)

There is a double polygon, but also the road does not match up inside vs. outside the park.

Here in Antietam, also in Maryland on our GIS:
![image](https://cloud.githubusercontent.com/assets/5996979/9038268/12242914-39c1-11e5-993c-a31c98b64ed1.png)

Again green is NPS, yellow is easement, white w/red outline is private with no easement.

Here is the same view from ParkTiles
![image](https://cloud.githubusercontent.com/assets/5996979/9038294/49827e56-39c1-11e5-8e2a-6e32d4840a11.png)

In this case, as much of the NPS owned part of the battlefield is in agriculture (crops, soybeans) with historic farm houses on the land. The private land is also agriculture and older homes, so it can be hard to tell where NPS boundaries are when you are there.

**Comment by makella** [comment]
@nateirwin the id's that were driving Park Tiles 3 in the compare tool are no longer available because I went through mapbox.com and deleted a bunch of test styles.  To get Park Tiles 3 to draw, you'll want to use the following:  `nps.dd9c9778,nps.816a5255,nps.9546ad31`

**Comment by nateirwin** [comment]
Thanks, switching now...

**Comment by makella** [comment]
closing. added both @ryanjhodge and @johnpauls boundary and labeling issues to places-data
