### ISSUE TITLE
update Places POI datasource in Park Tiles 2

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/park-tiles#161]
Jimmy would like us to phase out using nps.places_poi in favor of nps.nps-places-data (less data sources to maintain moving forward).

**Comment by jakecoolidge** [comment]
completed for slate, imagery, fused, and sound mapping projects

**Comment by jimmyrocks** [comment]
Thanks! This will keep all the POI stuff in one spot!

**Comment by makella** [comment]
Can someone write down all of the mapbox id's that we are supposed to be using in the maps?  Once everything is updated, we should go through mapbox.com and do a lot of cleaning up.

**Comment by jimmyrocks** [comment]
This specific issue is in reference to:
**nps.nps-places-data**

Once this issues is closed that should mean that nps.places_poi  is ready to be removed.

The only other mapbox datasource that I update is:
**nps.nps-places-boundaries**

That is the datasource used to build the boundaries, and it was last updated in April. Although that data source will get updated when [this issue](https://github.com/nationalparkservice/places-data/issues/103) gets closed.

I know there are older datasets in mapbox studio, but I don't know which maps point to which datasets. I can look into it to see if there's a way to generate a list based on projects currently hosted on mapbox.

**Comment by makella** [comment]
I think I've updated the maps that I need to.

For @mtaylorlong these are the layers in each one of the mapbox vector tile data sources that @jimmyrocks mentions above:

__nps.nps-places-boundaries__:  
- `#nps_park_polys`
- `#nps_park_points`
- `#nps_park_line` (Appalachian Trail only)
- `#nps_park_labels`
- `#nps_park_labels_15`

__nps.nps-places-data__:  
- `#nps_places_roads_and_trails`
- `#nps_places_polygons` (buildings and parking lots)
- `#nps_places_poi`
