### ISSUE TITLE
Proposed upgrades to Park Tiles 2

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#162]
I am thinking that we can easily make the following updates to Park Tiles 2 - the Fused version:

- labels (upgrade labels to what we have for version 3)
- display park boundary lines over water
- upgrade hillshade to v2 (when ready)

Since we won't be releasing version 3 until the beginning of next year, these might be some incremental changes (in addition to any others) that we can make to the current version.

If you have other suggestions and/or any comments on this, please post them here.

**Comment by makella** [comment]
city dots

**Comment by makella** [comment]
Hello All,

I've updated Park Tiles 2 with the changes above and some additional ones.  Please review if you have time:

http://www.nps.gov/maps/full.html?mapId=fcca1ee6-a010-4c7f-ae42-deafb351f77d

Thanks,
mamata

**Comment by nateirwin** [comment]
I think this looks great, @makella! No concerns on my part.

**Comment by makella** [comment]
ok, great.  one thing that i've been playing around with this morning in the blri map is refining place labeling a little more but maybe i'll just implement that in 3 or someone else can do that later on.

before release:
- clean up the project 
- adjust the poi layer to reflect the new labeling in this map
i would also like to:
- apply the styling to slate and imagery which has its own set of ripple down effects of other maps that need to be updated

**Comment by nateirwin** [comment]
Cool, I just created a new issue to track the release: https://github.com/nationalparkservice/park-tiles/issues/163.

**Comment by jakecoolidge** [comment]
I echo Nate's comment since the design decisions adhere closely to those in Park Tiles 3. A key difference is the use of OSM data within park boundaries, but I'm not detecting any conflicts or problems as a result. Instead, it reads more cohesively at large scales because it does not integrate Places roads/trails and buildings/parking lots.

**Comment by makella** [comment]
I also:
- removed the shadows from the roads
- adjusted the building color
- added airport icons 
- adjusted place labeling order and color
- ummmm and other small things

**Comment by makella** [comment]
@jakecoolidge thanks for the comments! yeah, just the regular pattern only with some carto enhancements

**Comment by jakecoolidge** [comment]
Overall the "volume is turned down"; just a little bit. I think it's a good direction. It's a little more subtle but still legible, and continues to prioritize NPS features (naturally).

**Comment by makella** [comment]
Closing.
