### ISSUE TITLE
Release Park Tiles 2.1.0

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/park-tiles#163]
Before release:

- [x] clean up the project
- [x] adjust the poi layer to reflect the new labeling in this map
- [x] apply the styling to slate and imagery which has its own set of ripple down effects of other maps that need to be updated  
- [x] make sure all POI layers have interactivity set
After release:

- [x] blog post
- [x] tweet

**Comment by makella** [comment]
I've finished up 2.1 redesigns for Park Tiles Fused, Park Tiles Imagery, and Park Tiles Slate. In addition, I've updated each map's POI overlay.

You can view the maps with their POI overlays using the URLs below (they are all in the mapbox-studio-projects repo in their respective park tiles directories in a 2.1 folder).

Fused:
http://www.nps.gov/maps/full.html?mapId=fcca1ee6-a010-4c7f-ae42-deafb351f77d

Imagery:
http://www.nps.gov/maps/full.html?mapId=e313427a-5ba2-4a1c-a302-3f7c26b0cdde

Slate:
http://www.nps.gov/maps/full.html?mapId=d4fde438-7708-4da4-af0a-48c80cc96267

@nateirwin do you want these to be associated with the 2.0 map ids or is it ok to keep those (for now) and update with these new ids?

@jakecoolidge I was wondering if you could try a different green for the Slate VC icon... I think it is really strong for the map.

As always, comments welcome.  I'm hoping that @mtaylorlong and @jakecoolidge can make any modifications or updates to these maps if there are comments/concerns before release.

mamata

**Comment by mtaylorlong** [comment]
I found one *incredibly minor* discrepancy (it may even be intentional): The Slate map is set to maxzoom 22 where the Fused and Imagery have maxzoom 21. @makella: is there a particular reason for this?

**Comment by makella** [comment]
Just an oversight... no biggie.  Also, in Builder our maps only display to zoom 19. Styles are so fast to upload so we just go all the way!

**Comment by nateirwin** [comment]
About the 2.0 vs. 2.1 map ids, I say we update the existing ones. That ensures all Builder maps using Park Tiles get upgraded. Unless you see a need to preserve 2.0?

**Comment by makella** [comment]
I can't see any reason why we need to... always nervous to override things but the projects are there in the repo if we need to revert.  I'm good with that.

**Comment by nateirwin** [comment]
:+1:

**Comment by mtaylorlong** [comment]
Adding to the checklist:
- [ ] Mamata save 2.1 tiles over existing 2.0 map id's
- [ ] Mamata publish old 2.0 tiles with new map id's
- [ ] @makella send @nateirwin new 2.0 id's for the compare tool
- [ ] @mtaylorlong updates readme files in mapbox-studio-projects repo
- [ ] Taylor takes new screenshots of park tiles 2.1 for use in builder
- [ ] Taylor goes through site to see if there are any other screenshots to update

**Comment by makella** [comment]
@nateirwin here are the updated id's for the compare viewer that we want to add in the announcement blog post:

__Park Tiles 2.0__
- Fused Map: nps.80b07a46  
- Fused POI: nps.6535e533  
- Imagery map: nps.b8902d58
- Imagery POI: nps.be61ce22
- Slate map: nps.3f21333e
- Slate POI: nps.779a58cf

__Park Tiles 2.1__
- Fused Map: nps.2yxv8n84
- Fused POI: nps.jhd2e8lb
- Imagery map: nps.gdipreks
- Imagery POI: nps.08c8af87
- Slate map: nps.68926899
- Slate POI: nps.502a840b

**Comment by nateirwin** [comment]
You all ok if I just link to the current compare interface? http://www.nps.gov/npmap/tools/park-tiles/compare/? I think it'll be hard to pare that interface down so it works well in the body of a blog post.

**Comment by makella** [comment]
I think the structure is OK... I was hoping to have the 2.0 Park Tiles, Imagery, and Slate maps with their POIs on the left and the 2.1 versions on the right.  

I don't think we need all the other map services for comparison unless that is written out in the blog post...

**Comment by nateirwin** [comment]
Humm... I was hoping to keep one unified interface. Mainly because I think it is really cool to be able to compare Park Tiles to other base maps, and I think it drives the whole point of Park Tiles home.

How about this: I take out Park Tiles 3 (for now), move the new Park Tiles 2.1 (with fused, imagery, and slate) to the left-hand side?

**Comment by makella** [comment]
I think the blog post needs to reflect that then.  Also, the other basemaps are more meant to show that the NPS has better data, right?  At this point, we aren't really using much NPS data so basically our map will look like the Mapbox map.

**Comment by makella** [comment]
I'm fine with either way, really.  I guess the other basemaps can show that we have our own style and where OSM data is better, the ones that don't use it will show that.

**Comment by nateirwin** [comment]
Pull request here: https://github.com/nationalparkservice/npmap-website/pull/60.

**Comment by nateirwin** [comment]
Blog post out and compare tool updated. Three more items for @mtaylorlong, then we can close this issue.

**Comment by jcant624** [comment]
Looking through Park Tiles 2.1, I noticed an error with a park label. Buck Island shows as "Buck Island Reef BUIS" instead of "Buck Island Reef NM". Thanks for adding marine boundaries. Looks great.
![capture](https://cloud.githubusercontent.com/assets/6653544/9368543/108c704e-4681-11e5-9fbb-08feb7588527.JPG)

**Comment by makella** [comment]
@jcant624 thanks for pointing this out!
I'm moving this issue to places-data.  You can follow progress here: https://github.com/nationalparkservice/places-data/issues/110

**Comment by nateirwin** [comment]
Rolling this out here shortly. Good job, everybody!
