### ISSUE TITLE
Park Boundary

### ISSUE THREAD

**Issue by avawser** [nationalparkservice/park-tiles#165]
Park boundary for Wind Cave NP in South Dakota is the old boundary. Ca. 5500 acres were added in 2011.

**Comment by makella** [comment]
@avawser thanks for letting us know! Do you have an updated boundary you can send us? Also, moving this issue to places-data where we track boundary updates: 
https://github.com/nationalparkservice/places-data/issues/111

You can respond there!

**Comment by makella** [comment]
closing here because issue is moved to places-data

**Comment by avawser** [comment]
We have a boundary that includes the new land but I'm not sure where we got it. I would check first with the MWR lands office to see what they have. If they don't have it we'll provide what we have.

**Comment by makella** [comment]
Ok, great.  You can follow progress of this issue at: nationalparkservice/places-data#111

mamata
