### ISSUE TITLE
Test out different methods for serving smaller map tiles

### ISSUE THREAD

**Issue by makella** [nationalparkservice/park-tiles#167]
We need to do some testing to see if there is a different image format we can publish our tiles for people using our maps with slower connections.

**Comment by cwlawlis802** [comment]
Is this something we are still looking to pursue @nateirwin?

**Comment by nateirwin** [comment]
At this point, probably not. We'll (hopefully) be switching to vector tiles for our mobile apps sometime soon'ish, and that should help with this. I'll go ahead and close.
