### ISSUE TITLE
Cut-off park label: Chickamauga & Chattanooga NMP

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/park-tiles#168]
![img_1788](https://cloud.githubusercontent.com/assets/10443/9500113/d0843d0a-4be0-11e5-9199-f0ee8aefacbc.PNG)

**Comment by nateirwin** [comment]
Related to #164

**Comment by cwlawlis802** [comment]
Are we good to close out here @nateirwin @mtaylorlong? The issue is no longer persisting.

**Comment by nateirwin** [comment]
Sure
