### ISSUE TITLE
GOGA not labeled

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/park-tiles#174]
Some feedback from the NPS.gov public comment form:

> I see that Ft. Point and Muir Woods are labelled, and the GGNRA is shaded green, but no label(s) on this incredible park! Please fix this.

**Comment by jimmyrocks** [comment]
The GOGA label was specifically removed from the map on April 30, 2014
because of conflicts with smaller nearby parks. This should be address in
Park Tiles 3.

**Comment by cwlawlis802** [comment]
This is being addressed here https://github.com/nationalparkservice/places-data/issues/240, including label points for all subunits and GOGA.
