### ISSUE TITLE
Campground symbols do not render consistently

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/park-tiles#175]
Moved here from: https://github.com/nationalparkservice/places-data/issues/341

At seeming odd levels and extents, campground symbols turn on and off. Campgrounds, arguably more cartographically significant than parking spaces and trailheads, should be symbolized clearly and consistently.

![](https://cloud.githubusercontent.com/assets/5861784/11955838/4abe679a-a883-11e5-8462-28c965ae29d1.png)

![](https://cloud.githubusercontent.com/assets/5861784/11955845/54d7f4ee-a883-11e5-9dc4-940c21227a20.png)

**Comment by cwlawlis802** [comment]
This no longer persists given the use of the POI overlay.
