### ISSUE TITLE
Render railroad ways

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/park-tiles#176]
Railroads are critical features for many parks - especially historic parks (Civil War battlefields, etc.). We should render them before the final release of PT3.

A good example is Steamtown National Historic Site:

http://insidemaps.nps.gov/places/editor/#background=mapbox-satellite&map=19.74/-75.67159/41.40931
http://insidemaps.nps.gov/park-tiles-3/#18/41.40831/-75.67013

Cc/ @mtaylorlong

**Comment by mtaylorlong** [comment]
I've been tracking PT3 issues in the places-data repo since many of them are intertwined with rendering (and since that repo is public). Do you think I should be tracking more of them here, or should we move this issue over to that repo?

**Comment by mtaylorlong** [comment]
I actually would love to track PT3 issues here. They just wouldn't be public since we don't want to expose the code behind our styles.

**Comment by nateirwin** [comment]
Humm, yeah it would be nice to make these issues public. But we don't want to expose some things for sure. Whatever you think is best...

**Comment by mtaylorlong** [comment]
I think it still makes sense to track them in the places-data repo and keep them organized with the park-tiles-3 tag. That way, when people give us feedback, I can send them links to the issue to track our progress.

**Comment by mtaylorlong** [comment]
Moved issue to places-data repo: https://github.com/nationalparkservice/places-data/issues/365
