### ISSUE TITLE
Add Private In-holdings

### ISSUE THREAD

**Issue by regan-sarwas** [nationalparkservice/park-tiles#177]
Unlike a fixed scale printed map with notes in the margin (i.e. HF Brochures), a web map (i.e. Park Tiles) can easily mislead a user who zooms into areas of private property within a park boundary.  A disclaimer is good, but easy to miss.  A polygon overlay with a clear "do not go here" symbology for private inholdings would be a great improvement.

**Comment by mtaylorlong** [comment]
Hi Regan. I saw that you opened a duplicate issue in the places-data repo for this. Since places data and park tiles are so intertwined (and since the park-tiles repo is private) we're tracking all these issues in the places-data repo. I'm closing this issue so we can track it in places-data.
