### ISSUE TITLE
Some labels might need additional NP or NHP

### ISSUE THREAD

**Issue by MappingKat** [nationalparkservice/park-tiles#83]
![screen shot 2014-08-19 at 12 15 27 pm](https://cloud.githubusercontent.com/assets/1077436/3970684/e07420ce-27cc-11e4-93ab-4369f337a29b.png)

**Comment by makella** [comment]
This will be implemented in Park Tiles v3.  Will keep this open until that is published.

**Comment by makella** [comment]
In version 3
