### ISSUE TITLE
Park Boundaries get wonky on zoom in.....

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/park-tiles#92]
Glenn Canyon...
http://www.nps.gov/npmap/park-tiles/#11/37.9456/-110.1888
Then...
http://www.nps.gov/npmap/park-tiles/#13/38.0184/-110.0827
Then...
http://www.nps.gov/npmap/park-tiles/#14/38.0199/-110.0508

Note how a block of the boundary detaches itself?

![image](https://cloud.githubusercontent.com/assets/5861784/4024855/ed9b1578-2bdc-11e4-914c-17ab8edc2f7c.png)

Smokies

http://www.nps.gov/npmap/park-tiles/#15/35.5638/-83.2184

![image](https://cloud.githubusercontent.com/assets/5861784/4024859/0ce61dc4-2bdd-11e4-922a-ccd689faa301.png)

Chrome Version 36.0.1985.143 m and Internet Exploder

**Comment by makella** [comment]
This has been resolved.
